stages:
  get-data:
    cmd: python3 scripts/data_scripts/get_data.py
    deps:
    - scripts/data_scripts/get_data.py
    outs:
    - data/raw/macro.csv
    - data/raw/submission.csv
    - data/raw/test.csv
    - data/raw/train.csv
  data-preprocessing:
    cmd: python3 scripts/feature_engineering_scripts/data_preprocessing.py
    deps:
    - data/raw/macro.csv
    - data/raw/test.csv
    - data/raw/train.csv
    - scripts/feature_engineering_scripts/data_preprocessing.py
    outs:
    - data/baselines/macro.csv
    - data/baselines/test.csv
    - data/baselines/train.csv
